### ISSUE TITLE
Sprinting not working

### ISSUE THREAD

**Issue by Okabintaro** [Okabintaro/SubmersedVR#10]
Double check if sprinting is not working, or if the action maybe is not bound properly.

**Comment by Okabintaro** [comment]
Sprinting is actually working. You automatically run/sprint based on how much you move the thumbstick.
There are two different unused modes though which read the button to toggle sprint or hold to sprint. Both not as intuitive though.

**Comment by LuigiEP** [comment]
no its not i dont automaticlly sprint i must swith to my pc to run and geht in the aurora an then swap again at VR pls fix this or make a option for key binds im on The Meta quest 3 with touch controler

**Comment by StaleC00kie** [comment]
Yeah, sprinting is 100% not working. Sprinting is supposed to make a different sound effect, and right now, it doesnt.
