### ISSUE TITLE
Can't see hands even after typing -vrmode openvr to the advanced launch options of the subnautica game

### ISSUE THREAD

**Issue by Subnauticcafan234** [Okabintaro/SubmersedVR#101]
I tried everything, still now working, and yeah i have -vrmode openvr written in advanced launch options 
![зображення_viber_2024-01-03_19-29-33-998](https://github.com/Okabintaro/SubmersedVR/assets/155570992/89a369aa-83c1-430a-b8f1-d9e9750dd99d)

**Comment by Subnauticcafan234** [comment]
![image](https://github.com/Okabintaro/SubmersedVR/assets/155570992/4e91bc10-0dfa-47fd-beb4-ae39ff1bcee5)
so here the image of it

**Comment by Okabintaro** [comment]
Did you start the game from the steamvr dashboard? What headset do you use?

**Comment by Subnauticcafan234** [comment]
i use oculus quest 2, i started just from steam

**Comment by Okabintaro** [comment]
Try starting it from steamvr dashboard then. Steamvr has to be running before you start the game

**Comment by Subnauticcafan234** [comment]
> Did you start the game from the steamvr dashboard? What headset do you use?

i use oculus quest 2, i started from steam (not vr dashbord)

**Comment by Subnauticcafan234** [comment]
> Try starting it from steamvr dashboard then. Steamvr has to be running before you start the game

thx man, helped
