### ISSUE TITLE
It is impossible to disassemble the buildings

### ISSUE THREAD

**Issue by Amputator666** [Okabintaro/SubmersedVR#103]
I can't find the key to dismantle buildings. The controllers are identical to Oculus Quest 2 (Headset is HP Reverb G2. The layout in Steam VR is appropriate.

**Comment by Okabintaro** [comment]
Please look at the steamvr bindings of the game. Maybe you need to adjust them. The button prompts are not accurate, see #4

**Comment by Amputator666** [comment]
> Пожалуйста, посмотрите на привязки игры к steamvr. Возможно, вам нужно их скорректировать. Подсказки кнопок неточны, см. [# 4](https://github.com/Okabintaro/SubmersedVR/issues/4)

Thanks, I figured it out: the right controller stick is used as a d-pad.

**Comment by Amputator666** [comment]
Problem solved.
