### ISSUE TITLE
the review on the right stick did not work, now it almost does not work at all

### ISSUE THREAD

**Issue by Wayfarer976** [Okabintaro/SubmersedVR#110]
Good afternoon, I wanted to ask for help with the VR mod again. I had a problem with the non-working stick of the right controller, more precisely, with the fact that the "look" command tied to it did not work (by the way, after trying to reconfigure the control, I found out that any commands containing "..look.." they did not work on any button, the game allowed you to look around only with a helmet, and you could try to get used to this style of play, but when using any means of transportation, they do not respond to the control of turning your head, and the buttons do not work).
I tried various options several times, reinstalled the game completely, but nothing helped, and then I decided to reinstall Steam VR.
And it gave its results :))) After steam VR, I installed the game and the mod, but when starting the game, now the game menu is loaded into the helmet and nothing (almost) works at all, a pointer beam stretches from the forehead, but when the helmet is shifted, it still hangs in the air, there are no controllers in any form, and in the logs as I understood there were a lot of errors, but I don't understand what they mean, and why this happened after reinstalling steam VR. Please tell me what can be done, I would appreciate it.
The game is Subnautica
VR - Quest 2
I play through Virtual Desktop
installed:
1 - BepInEx.Subnautica BepInEx 5.4.22
2 - Immersive Virtual Reality version 0.1.6 - 2023-05-10
when starting the game, "-vr mode openvr" is indicated
[changelog.txt](https://github.com/Okabintaro/SubmersedVR/files/14084121/changelog.txt)
[LogOutput.log](https://github.com/Okabintaro/SubmersedVR/files/14084122/LogOutput.log)

**Comment by Wayfarer976** [comment]
[LogOutput.log](https://github.com/Okabintaro/SubmersedVR/files/14086358/LogOutput.log)

New file with mistakes

**Comment by Okabintaro** [comment]
There is no error for the mod in the logs. Maybe try reset the bindings in the steamvr dashboard. They could be misconfigured.

**Comment by Wayfarer976** [comment]
I'm sorry, but how do I reset the bindings in the Steamvr control panel? I don't quite understand what it is, and where to find it.

**Comment by wulf21** [comment]
> I'm sorry, but how do I reset the bindings in the Steamvr control panel? I don't quite understand what it is, and where to find it.

In VR there is a SteamVR overlay while you are playing in SteamVR. On other controllers, the system button opens it, but I don't know if Quest passes that through or opens some Quest menu instead. If you can't open it in VR, then you can open it on desktop. There should pop up a small SteamVR window while playing. Go into the menu on the window (three stripes on upper left) and go to devices -> controller settings. Open the button to change controller configuration. If it says "User Defined" set it to "Standard/Default" instead.

**Comment by xNattefrostx** [comment]
I have the same issue and nothing is fixing it the right stick just does not work. Everything is installed correctly and im using the epic store version, and when you go into the settings for the controllers in subnatica ( not steam settings ) it shows up as button 17 if you push the stick in any direction.

**Comment by yunyuyuan** [comment]
same problem in quest3, using steamVR

**Comment by Wayfarer976** [comment]
Greetings to all. Unfortunately, all my efforts went to waste. I installed both ”QModManager“ and ”BepInEx“ and "Tobey's BepInEx Pack for Subnautica-1108-5-4-23- payload-2-3-0-1728326422”, I bet on them in various variations – “VR Enhancements v3.1.2 for Steam”, “SubmersedVR_0.1.6”, “SubmersedVR_0.1.0” (having previously deleted the previous changes made). I did this sometimes by completely deleting/installing the game itself. But nothing helped, sometimes the “build” did not work, sometimes there was no VR, and when it was, the review (on the right stick) did not work. Everything works, and "BepInEx Tweaks-1104-1-2-1-1687269191” and “Subnautica Mod Manager v1.2.3-1168-1-2-3-1723080382”, everything can be set, but there is no way to achieve the execution of the “look ...” command. Is there someone who has already encountered this and knows the solution? Perhaps somewhere in the Steam or Steam VR settings, some kind of check mark / setting for the game or generally common to all VR games is frozen, and now it does not allow any game settings and mods to work? How is the principle of subordination implemented, what is more important than Steam or a Game or a Mod, where can there be a plug? I'm not a programmer and I'm trying to find a clue just by logic, maybe there's someone who understands the subject? The stick itself is working, and the other commands assigned to it are working. Only the “look” command and all containing “look …" do not work where don't assign them. Turning is possible by turning the head or the whole body (in fact, by turning the helmet), but this does not work when controlling equipment, in it I just turn my head and look at the sides, and the equipment moves in a straight line. This is the situation for both Quest 2 and Quest 3. Just in case, I emphasize - the game is Subnautica. Help!!!!!

**Comment by Wayfarer976** [comment]
I apologize for the verbosity, new information has been added. I decided to take it from a friend and try to connect a PlayStation controller, I thought if anything, buy a similar one and then play on it. And then an amazing fact turned out, all the “look …” commands do not work on him either. At the same time, I went further, completely reinstalled the game, and launched it not only without mods, but also in “flat” mode - and nothing changed. You can only look around in the “flat” mode with the mouse. Well, in VR mode, if you still install it - by twirling the helmet. In both cases, you can turn in transport only with the mouse. The problem is clearly in the Game settings, or Steam (and not even in Steam VR). But I can't find where and I don't even understand where this can be configured/changed. At the same time, judging by the fact that such a problem as mine is not often voiced, then everything works correctly for thousands of others?! If anyone has solved this quest, or knows where to look for settings, or can spend their time and knowledge to understand where this error / setting is hidden, I will be extremely grateful! Otherwise, I haven't been able to run the game like everyone else in VR for more than a year. And now it turns out that even in the flat version, I have crooked control.

**Comment by Wayfarer976** [comment]
**### Solving the problem with turning on the right stick.**

Well, my long-term problem has been solved. I had to try for a long time and hard myself, but in the end happiness came. I will describe how it turned out for me, if this method is suitable for you, please send a confirmation. Especially if there are any additions /clarifications.
Problem: the “look...” commands originally linked to the right stick of the Oculus Quest 2/3 controller, or to the right stick of the Xbox/PS_3-5 controller, did not work. Attempts to reconnect made no sense and success, on other verses/buttons, the commands continued to be dead. These errors were typical for both the “clean” version of the game and the game with mods.
In an attempt to somehow solve this problem, I went into Steam and right-clicking on “Subnautica” in the menu, selected “Properties”, then clicked on the “Beta versions” line and in the “Beta testing” drop-down list, I first selected “legacy” - the update was installed, I launched the game (in the “flat” version, I dug into the main menu and launched a new game, even tried to move around), but nothing changed. After that, I selected “experimental” in the drop-down list of “Beta testing” – the update was installed, I launched the game (in the ”flat“ version, rummaged through the main menu and launched a new game, even tried to move), but nothing changed. And finally, I chose “no” again in the drop-down list of “Beta testing” – the update was installed, I launched the game and HOORAY!!!!! Already in the “flat” version, the rotation control on the PS_4 controller stick started working, and then in VR on the right stick of the Oculus Quest 3 controller (for VR, I installed the SubmersedVR_0.1.6 mod). That's it, if you have something to add, write. If there is an understanding of how this “magic” worked, even more so. It is clear that when updating with “unstable” versions, the jackdaw / setting went back to normal somewhere, but there may be a clearer understanding of the situation.
