### ISSUE TITLE
Im have errors when trying to play subnatica VR. it wont its acting like its not loading submersed vr or something. it just plays as if loaded without mods.

### ISSUE THREAD

**Issue by LunarReefer** [Okabintaro/SubmersedVR#112]
i have enabled legacy build and used vortex for bepinex. I really tried to make sure I didnt mess anything up. ive succesfully modded skyrim, gta 5, and several emulated games incluiding switch games. anyways i did something wrong and i dont know how to read log files and comes to a solution. I pulled the logs and compressed them into a zip file so i wouldnt have to copy the entireity here. please help.
[bepinex logs.zip](https://github.com/Okabintaro/SubmersedVR/files/14146178/bepinex.logs.zip)

**Comment by Okabintaro** [comment]
I took a look at the logs and yea, please use a newer version of subnautica. The legacy branch won't work. Thanks!
