### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by foochi81** [Okabintaro/SubmersedVR#129]
I used vortex and downloaded bepinx and submersed and copied the files over and all that good stuff but it still isnt working. In the logs theres only 3 warnings: [Warning:SubmersedVR] Game was not started in VR. Don't load and apply SubmersedVR patches.

[Warning: Unity Log] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[Warning: Unity Log] Can't set camera projection to orthographic when XR is running and rendering to the main view. Camera is no longer valid to use for rendering. Please check camera projection settings of all camera components in your scene.

also I set the -vrmode openvr

any ideas?

**Comment by Okabintaro** [comment]
The log is too short, I am not sure what the issue is. Feel free to upload the whole log and reopen the issue.
