### ISSUE TITLE
Xbox store version not working 

### ISSUE THREAD

**Issue by FirebirdR11** [Okabintaro/SubmersedVR#131]
I have subnautica from the Xbox store version running on my quest 2 via link cable. I have set everything up with nexus and when I launch subnautica my oculus controllers act as a standard controller and my quest displays the game as if it were a flat screen, able to look around but the menu is static and half out of view. 
I have a feeling the issue might be that I can't force the game to launch in steam vr due to it being from the Xbox store.

Does anyone know a fix for this?

here's the bepinex log
[LogOutput.log](https://github.com/Okabintaro/SubmersedVR/files/15444361/LogOutput.log)

Update:
i have tried using steam link to stop the oculus runtime and now instead of launching with the whole screen offset:
If i launch from steam vr (ive added the microsoft version of the game through uwphook) it will launch normally, this is probably because it gets put under a weird launch option.
Or B, the screen goes white and the game crashes
i have tried using Vorten for the bepinex and manual install which have both worked fine for other mods but wont work for the submersed vr mod.

i think this is due to the fact it is the ms version thats all of these issues are happening and why it doesent work but i would like an indefinite answer please.

bepinex eror in log:
Missing platform services, returning default display mode

**Comment by Okabintaro** [comment]
Yeah, last time I checked the MS version was outdated. Only the most recent versions that are shipped with Steamvr and Epic worked for me.

**Comment by Okabintaro** [comment]
I can't do much about this, but added a note to the README about it.
