### ISSUE TITLE
Can't change equiped item

### ISSUE THREAD

**Issue by CillyCil** [Okabintaro/SubmersedVR#132]
I just compiled the mod and on Quest 2 controllers I cannot figure out how to equip items and switch between them. I think documenting the bindings would be very beneficial especially for those of us who are lost.

**Comment by CillyCil** [comment]
After further investigation I believe this is a bug with this commit. Clicking the joystick shows the menu but it's stuck to your hand so you can't select anything.

**Comment by Okabintaro** [comment]
The menu you have is a half life alyx inspired menu. You can see it in this devlog: https://youtu.be/sWq2Tl6JJCs?si=2OBXGv7EImwJHQY9

But I agree that some written documentation should be done.

**Comment by CillyCil** [comment]
My issue was I have space drag mapped to clicking my joysticks in OVR Advanced Settings, this was my bad
