### ISSUE TITLE
Prawn movement is erratic (and forwards movement seems impossible)

### ISSUE THREAD

**Issue by condescendingGerminator** [Okabintaro/SubmersedVR#135]
Idk if you're responsible for the Subnautica BZ grip controls for the prawn, sorry if you aren't :|
The prawn's controls are a bit weird, you can't even move forwards and it seems to just change direction and spin on a whim.
I can maybe post a showcase of the bug, I'm also unsure whether this is due to poor battery life/bad network.

**Comment by Okabintaro** [comment]
Are you referring to the VR driving feature?
I think it works but you have to get used to how the controls work. It's like you are using a joystick that is very sensitive.
I would suggest turning that feature off if its not to your liking, since the normal controls should work fine too.

**Comment by condescendingGerminator** [comment]
it was long as hell ago i figured out the controls already, but thanks!
