### ISSUE TITLE
How do i save my game?

### ISSUE THREAD

**Issue by Ultimatefsc** [Okabintaro/SubmersedVR#147]
recently-ish started using submeresedvr, and i cant find any keybinds on my controllers to pause, save, then quit! I lose all my progress! 
If there isnt a fix, im happy for a "menu in pda" mod or something.
Quest 3 user.

**Comment by Okabintaro** [comment]
There should be a big Menu button on the bottom right corner in the PDA already. If you don't see that the mod probably isn't installed properly.

**Comment by Ultimatefsc** [comment]
> There should be a big Menu button on the bottom right corner in the PDA already. If you don't see that the mod probably isn't installed properly.

Ahh, Thankyou!
