### ISSUE TITLE
Very werid error. Mod just won't work. Good luck figuring out this one. 

### ISSUE THREAD

**Issue by LordArachness** [Okabintaro/SubmersedVR#155]
No hands show up. The mod just doesn't work. Very strange error.

[LogOutput.log](https://github.com/user-attachments/files/17468660/LogOutput.log)

**Comment by NibblyPig** [comment]
MissingMethodException suggests that Belpin's hooks are not working properly, what version of the game are you running, a fresh Steam installation?

**Comment by robrelf19** [comment]
I had the same issue.  Rift S.  Resolved it by manually starting SteamVR manually, stopping fpsVR, then running Subnautica from within Steam using the -vrmode openvr launch option.  Hope this helps.

**Comment by Okabintaro** [comment]
Actually in this case it seems you were using an old version of Subnautica.
The mod only works with the most recent version of the game.
Neither `experimental`  or the `legacy` branch are supported.
