### ISSUE TITLE
Just not working.

### ISSUE THREAD

**Issue by TheCelticTiger** [Okabintaro/SubmersedVR#156]
I have no error codes, nothing. I followed the instructions, and loaded it up, and...nothing. It just doesn't work.

**Comment by Hue-G-Rection** [comment]
having the same thing, is installed but controllers wont show up in menu. tried reinstalling both game and mods but nothing.

**Comment by Okabintaro** [comment]
Can you guys give more information? What headset do you use? What streamer? 
Do you use airlink?

**Comment by TheCelticTiger** [comment]
I use an Oculus on Steam. And I use the airlink, yeah. It's an Oculus 1. (I'm poor. x.x)

**Comment by Hue-G-Rection** [comment]
I’m using the same set up. Quest 1 via airlink to steam. I’ve also tried my quest 2 with steam link to no avail.

**Comment by Okabintaro** [comment]
Ah thanks. Yeah I am getting more and more reports of people having issue with link and airlink.
Just to be sure, you followed the [last step in the README](https://github.com/Okabintaro/SubmersedVR?tab=readme-ov-file#installationsetup)?

> Start the game within SteamVR. The Oculus Runtime won't work and is not supported!
> For OculusRift or Oculus Link Users: You can force the SteamVR runtime by adding -vrmode openvr [to the advanced launch options of the Subnautica game](https://help.steampowered.com/en/faqs/view/7D01-D2DD-D75E-2955). Please make sure you did that before launching the game.

I will try to setup up link on my quest on the weekend again and see if I can reproduce and troubleshoot any issue if needed.

**Comment by Okabintaro** [comment]
I just setup the game to use airlink on my quest 3 and it works perfectly fine.
You need to make sure to first start steamvr and then launch the game from witihin the steamvr dashboard.
For Installing the mod I found this tutorial the most clear: https://youtu.be/4OSVtCSQpOE?si=0g--A8ezEa0C9QKg
You need to copy the whole folder with the data, otherwise it won't work.

**Comment by Okabintaro** [comment]
Also note that neither the `legacy` or `experimental` beta branch is supported.
I reinstalled the game, 0.1.6 Version of the mod and used the latest BepInEx Release here: https://github.com/toebeann/BepInEx.Subnautica/releases/tag/v5.4.23-payload.2.3.0
