### ISSUE TITLE
How to recharge a device?

### ISSUE THREAD

**Issue by Patola** [Okabintaro/SubmersedVR#18]
I can't figure this out, sorry if it's obvious and I can't see it. I hold the device in my right hand (e.g. the scanner) and I press the left controller [A] button, I see the old battery and a new battery I have in my inventory. But I can't click on any of them, I can't figure out how to select it for it to be replaced.

**Comment by Okabintaro** [comment]
You should be able to use the left joystick to cycle in the menu and then click A on the right controller to swap them.
There is no laserpointer or touch UI for that yet.

**Comment by Patola** [comment]
Tried just that, doesn't seem to work. I am using Valve Index knuckles. The left controller works correctly for turning, when I have the seaglider at my hand and press the left controller A button it shows a "X" at the left, my depleted battery at the center and a charged battery at the right. I tried pressing the left controller joystick in all directions, nothing happens, nothing is selected and pressing left A again just turns off the battery overlay. Also tried using the right controller joystick or other controls but nothing seems to select the battery to replace. I can send a screenshot if it would get easier to understand.

**Comment by Patola** [comment]
Will do, thanks. I'm using Linux, maybe that did something different. Nevertheless, will check the bindings.

**Comment by Okabintaro** [comment]
Oh, you have success running Subnautica on Linux? That's awesome.
For me I got really bad reprojection errors due to a VSync bug and ALVR.
I would love to test and develop on Linux too.

Feel free to reach out on Discord: I'm Okabintaro#4177 on there.

**Comment by Patola** [comment]
Hey, you were right. The left stick was set only to "work as left stick" and no extra binding. I understand what you said to map joystick left to "left+previous tool" and joystick right to "right+next tool" (I don't recall the wording on the input setup screen) but I though better to map left joystick click to "left+previous tool" and right joystick click to "right+next tool", everything works nice on this configuration and that solved my problem. I was also able to better understand the bindings, e.g. right controller touchpad south as "deconstruct" which was something I wasn't able to do so far.

**Comment by Okabintaro** [comment]
Glad you got it working 👍🏼
