### ISSUE TITLE
Subnautica update broke SubmersedVR

### ISSUE THREAD

**Issue by Patola** [Okabintaro/SubmersedVR#19]
Seems that the latest Subnautica update (which bumped up the .net version amongst other stuff) broke SubmersedVR and the mod is not working anymore. The BepInEx log window spits a lot of red warnings/errors and the game uses its "normal" VR with glance-based selection.

Not sure if another bug report should be reported in the BepInEx for Subnautica repo... 

This is the update that broke SubmersedVR: https://store.steampowered.com/news/app/264710?updates=true&emclan=103582791435169353&emgid=3657523793500556027

**Comment by Okabintaro** [comment]
Ah thanks for the heads up.
From the changes it looks like they fixed the black screen bug now, which I also fixed, so maybe there is problem there.

I will try to update the mod tomorrow for the new release.

**Comment by Patola** [comment]
In the meantime, [reverting back to the old version](https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994) works:
```
download_depot 264710 264712 7985964044056395698
```
(takes a while, ~7GB of content needs to be downloaded and it's way slower than regular steam download)

**Comment by Okabintaro** [comment]
Should be fixed in v0.1.5: https://github.com/Okabintaro/SubmersedVR/releases/tag/0.1.5
