### ISSUE TITLE
Right stick does not work to look around

### ISSUE THREAD

**Issue by magisoft-studios** [Okabintaro/SubmersedVR#23]

**Comment by Okabintaro** [comment]
Please provide more information. The mod is only tested with quest and index controllers right now. For other controllers you might need to make your own binding.

**Comment by magisoft-studios** [comment]
I just bought Subnautica on sale on Steam today.  I think I followed all
instructions to download and install your Mod (thanks so much for doing
this!).  I launch the game via Steam VR and try to play on my Quest 2 using
the Quest 2 hand-held controllers.  The game loads fine and I can start
playing.  When I get to the first scene in the crashed life boat or
whatever it is the game tells me to use the right stick to look around.
The right stick does not do anything.  The left stick works fine, I can
move forward/back/right/left with it.  The other buttons like A, B, X, Y
also seem to work.  I can interact with the fabricator, pick up and use the
fire extinguisher, climb the ladder, jump into the water and swim around,
etc.  It is only the right stick that does not seem to work. By the way, I
can look around with my headset with no problem.  I can also physically
turn my whole body and turn around no problem.  It is just trying to use
the right stick to turn/look around that seems to not work.  And it seems
that if the only way to turn/look around is to actually physically move
then that is just not going to be a great experience.

I researched for a while and found lots of hits on the web about the right
stick not working under different circumstances, for Oculus/Quest in
general, for Steam VR, for Subnautica with the earlier VR Enhancements mod,
etc., etc.  Honestly, I can't filter out all the noise of all the different
posts in different forums, so I was wondering if you have some idea if it
is specific to your mod or not, or any suggestions for me.

What other details do you need to help figure it out?

Thanks for any help,
Tom

**Comment by magisoft-studios** [comment]
So I tried a whole bunch of "fixes" from the Internet.  Not sure what
finally did the trick but now the right stick is working well.  I am having
a great time!  Thanks for doing the mod!

**Comment by Okabintaro** [comment]
Glad you got it working!

**Comment by plenaerts** [comment]
We have the same issue on a quest 2. We'll be looking into the controller bindings.

**Comment by Wayfarer976** [comment]
I have the same problem with the inability to view the stick of the main quest 2.
The game is Subnautica
VR - Quest 2
I play through Virtual Desktop
installed:
1 - BepInEx.Subnautica BepInEx 5.4.22
2 - Immersive Virtual Reality version 0.1.6 - 2023-05-10

**Comment by Okabintaro** [comment]
Can you please post log files? Are all the other buttons work fine? Make sure to follow the install instructions carefully by copying the whole mod folder.
You might have to look into the steamvr bindings yourself and reset them to default or adjust them.

**Comment by plenaerts** [comment]
My issue is resolved. The mods were not loaded.

Pieter
________________________________

**Comment by Wayfarer976** [comment]
> Can you please post log files? Are all the other buttons work fine? Make sure to follow the install instructions carefully by copying the whole mod folder. You might have to look into the steamvr bindings yourself and reset them to default or adjust them.

Everything else works fine. No command containing "Look" works, I would not try to bind it to any button/stick. I install the mod not for the first time and not for the first time, everything is according to the instructions. Unfortunately, reconnecting the control buttons in the Steam does not do anything, as I have already said, any command containing the word "look" does not work at all. I found an interesting detail, the real game layout of the mod in the Steam appears only AFTER starting the game, before that, when I try to go into the controller settings in the Steam, I find something awkward - having nothing to do with the game, and the real commands themselves that can be assigned to control the game are not there. All this appears after starting the game, as if on top. But look doesn't work. How to upload magazines and which ones, I will be happy to do, hoping for help, the game and mod are just awesome, and I really want to achieve normal operation, especially it's a shame that most of them work, at least with a question like mine, not so many people on the network. The Steam game launch line says: "-vrmode -openvr".
