### ISSUE TITLE
Keyboard gets stuck in loop when naming locker. Never closes, locks up game. 

### ISSUE THREAD

**Issue by Branes51** [Okabintaro/SubmersedVR#26]
This happens virtually every time. I usually accidentally click on the name trying to open the locker. Another issue. The trigger and joystick movements are very fast. It's very difficult to get precise depth or direction. That being said, the mod is fantastic. I love the survival meters on the wrist.

**Comment by Branes51** [comment]
Just an FY I've discovered it does it anytime something gets named. Beacon, seamoth in the Vehicle Upgrade Console. etc. The workaround is easy. Just go into the non VR version and make the changes and save it. Then go back to VR, the changes will be saved.

**Comment by Okabintaro** [comment]
Yeah I think it is a regression from the latest update.
You can also open and close the steam dashboard to make it disappear afaik.

**Comment by Branes51** [comment]
Is there a way to control the speed of the up and down movement with the triggers? It's really hard to control. Trying to get through doors is a chore. Even a light touch moves you up or down too much.

**Comment by Okabintaro** [comment]
Not yet. You  can suggest a way to change this in a new issue if you would like.

**Comment by Branes51** [comment]
the only thing I can think of is a sensitivity setting like some games have for mouse or joysticks. No clue how you would do that though. Also, can't seem to find a way to sprint on land using controllers.

**Comment by Brusura** [comment]
> This happens virtually every time. I usually accidentally click on the name trying to open the locker. Another issue. The trigger and joystick movements are very fast. It's very difficult to get precise depth or direction. That being said, the mod is fantastic. I love the survival meters on the wrist.

As a workaround, Fast double "click"  with trigger works
