### ISSUE TITLE
Player drifting to the right

### ISSUE THREAD

**Issue by Tuupertunut** [Okabintaro/SubmersedVR#29]
When staying still, the player is constantly drifting to the right and also a bit backwards, with a speed of around 0,1 m/s. Also when pressing the move up and move down keys, the player moves quite a bit right.

I'm experiencing this using a Samsung HMD Odyssey Plus and my new key bindings for Mixed Reality controllers from PR #28. Is this happening only for me or with other configurations too?

**Comment by Okabintaro** [comment]
I never had that problem on the Quest 2 myself.
You don't think it is controller drift maybe?
I wanted to implement a deadzone for the analog inputs into the mod but I think you can do that aswell in the steam vr input.

**Comment by Tuupertunut** [comment]
It could be controller drift in the left joystick used for movement. It's good to know that it doesn't happen for everyone.

However when using the move up and down keys, the player is not just moving slightly to the right but at full speed (in addition to moving up or down). Could this be caused by controller drift too? One explanation could be that when the player is moving both up and sideways, the sideways velocity would not depend on the joystick anymore but just be at full speed.

**Comment by Tuupertunut** [comment]
I tested it: yes, it is controller drift. My joysticks were showing values between -0.05 and 0.11 while in neutral position. They required a 16% deadzone from SteamVR settings to completely stop drifting.

Indeed, it is also true that while moving both up/down and sideways, the sideways velocity always goes to full speed, regardless of joystick position. This caused the huge sideways drift while moving up/down.

**Comment by Tuupertunut** [comment]
I think the 100% up/down velocity issue should have its own issue.
