### ISSUE TITLE
Virtual Desktop support?

### ISSUE THREAD

**Issue by garrsco** [Okabintaro/SubmersedVR#34]
Hello,

Does not appear to work with Virtual Desktop (my preferred wireless link for Quest 2).  A) How do I uninstall SubmersedVR?  Or B) is there a way to make it work?

Thank you, much appreciated. :)

-g

**Comment by Okabintaro** [comment]
Yes, that is how I tested the game. It should just work if you [followed the instructions](https://github.com/Okabintaro/SubmersedVR#installationsetup) carefully.

There is not enough information in your descritption to help. What is the problem? Do you get the BepInEx Console at all?

To uninstall it, just remove the SubmersedVR.dll from the plugins forlder.

**Comment by garrsco** [comment]
Interesting, ok, thank you.

Here is what happened:

I launched the game from inside the goggles, via Virtual Desktop.  I noted that a lot of command line code was running on the (non virtual) desktop screen.  The game then fired up inside the goggles.  However, the video was EXTREMELY laggy-- every time I moved my head, a chunk of the screen would freeze then move.

Now that I know it SHOULD work, I'll go over the instructions again and see if I missed something.  Thank you!

**Comment by garrsco** [comment]
PS - I think the "BepInEx Console" is the command prompt with lines of code that flash by...  But it doesn't stay open so that I can review the commands and results.

**Comment by garrsco** [comment]
I uninstalled SubmersedVR and am having the same performance issue.  So it must be a problem with the latest Subnautica update or perhaps another mod.  Apologies.

**Comment by Okabintaro** [comment]
No worries. You can try just installing SubmersedVR and BepinEx if you would like.

**Comment by garrsco** [comment]
Do you mean without BepInEx Tweaks and Configuration Manager?  (Or do you mean removing all other mods...)

**Comment by Okabintaro** [comment]
I would just add SubmersedVR and BepinEX and then readd all other mods until you hit the problem, that way you can figure out which mod is causing the issue.

**Comment by garrsco** [comment]
I gotcha.  Makes sense.  Thank you for the quick help-- hopefully I can get this working; excited to try your mod. :)
