### ISSUE TITLE
Right thubmstick rotation feels weird

### ISSUE THREAD

**Issue by hearth1an** [Okabintaro/SubmersedVR#38]
Hey! Finially I'm really enjoying Subnautica with such mod, big thanks! 
For me it feels very weird and uncomfortable when I suddenly use right thumbstick and the view rotates. Currently I'm using inventory button to reset the view. I wish there be an option to lock rotation smh at all or to the head movements. Not sure if anyone having the same issue tho

**Comment by Okabintaro** [comment]
You can add a deadzone on steamvr to the thumbsticks I think or try out the new snap turning feature now.
