### ISSUE TITLE
Snap Turning 

### ISSUE THREAD

**Issue by Okabintaro** [Okabintaro/SubmersedVR#39]
Check compatibility with snap turning mod or add an option for it.

**Comment by Okabintaro** [comment]
Basic snap turning got added now, might reopen later if there is a need for vehicle snap turning too.

**Comment by benjamincheng10** [comment]
OMG thank you SOO much for adding snap turning! this makes playing seated so much better! PLEASE add snap turning for all the vehicles please, the way vehicles turns makes me nauseous.

**Comment by Chrisneb1** [comment]
Yes, thank you so much for developing this amazing VR mod! I would love snap turning for vehicles too. Seamoth makes me nauseous after only a few minutes.

Unfortunately this other snap turn mod isn't compatible with SubmersedVR (the best VR mod IMO):
https://github.com/ethanfischer/SubnauticaSnapTurningMod
