### ISSUE TITLE
No menu access in game

### ISSUE THREAD

**Issue by Zartnal** [Okabintaro/SubmersedVR#45]
Once I'm in the game, I can't access the menu. So I can't save :'( 
None of the buttons on the controller correspond to the menu. 
The keys on the keyboard seem to be disabled, so I can't bring up the menu either.
Also in the main menu, key settings are no longer accessible. It is therefore impossible to customize the menu access key.

**Comment by Okabintaro** [comment]
There is a menu button in the PDA. All the bindings/controls can be changed in the SteamVR bindings menu.
