### ISSUE TITLE
No motion controllers and camera is above the menu when starting game with SubmersedVR

### ISSUE THREAD

**Issue by ThrowawayTheSecond** [Okabintaro/SubmersedVR#48]
When I run the game in steamVR and stream to oculus quest 2 via Airlink with this mod, I have no motion controllers and none of the buttons on the controllers are working, so I am unable to select anything from the menu. The vr camera is also above the menu, recentering places the camera in the correct position.
![screenshot](https://github.com/Okabintaro/SubmersedVR/assets/138209527/37153119-156c-4ef3-a02c-1056aada7d19)

**Comment by Okabintaro** [comment]
Please make sure to follow the README guide properly. You most likely forgot to set the launch commands on steam.
If not please upload a logfile.

**Comment by ThrowawayTheSecond** [comment]
I did write -vrmode openvr into the subnautica launch options, where do I find a logfile?

**Comment by Okabintaro** [comment]
It is in `Subnautica\BepInEx\LogOutput.txt`. You might also want to join the [Flat2VR](flat2vr.com) for better support.
The issues here are used for feature requests and bug reports. Thanks!
Alternatively you could also use the [discussions](https://github.com/Okabintaro/SubmersedVR/discussions).
