### ISSUE TITLE
No hands showing

### ISSUE THREAD

**Issue by BeatSaberGuy2** [Okabintaro/SubmersedVR#64]
When i start the game no controllers or hands show up but when i use the joystick i am able to navigate some of the menu, i managed to get into a save but no hands where showing and my controllers werent appearing in the game.

**Comment by BeatSaberGuy2** [comment]
im using the legacy version of the game with an oculus quest 2 plugged into my pc

**Comment by Okabintaro** [comment]
The legacy version unfortunately is not supported by the mod.

**Comment by BeatSaberGuy2** [comment]
ok
