### ISSUE TITLE
In game keyboard

### ISSUE THREAD

**Issue by GaratJax82** [Okabintaro/SubmersedVR#68]
Feel free to delete if this outside the scope of the mod. 
Would it be possible to connect the VR  virtual keyboard (where available) in the game? 
Example, when selecting a beacon/ locker label a virtual keyboard appears and allows you to type in label names. 

Thanks!

**Comment by Okabintaro** [comment]
Hm? This should already be in the mod.
If you select a locker or beacon the SteamVR keyboard should open up.

**Comment by GaratJax82** [comment]
Odd, I wasn't seeing anything pop up. It's probably something to do with my setup. I'll play around with the settings on steamVR tonight. See if I can get it to show up. 
Thanks.

**Comment by GaratJax82** [comment]
update: got the keyboard to work. apologies for the confusion.

Great mod!
