### ISSUE TITLE
Can it work without steam.

### ISSUE THREAD

**Issue by Spider274** [Okabintaro/SubmersedVR#73]
I have this game through game pass PC along with my rift s. Is this mod only for Steam VR because I cannot run it on my PC with the mod. I have installed Bepln Ex directly into the files and correctly followed the installation instructions.

**Comment by Okabintaro** [comment]
Unfortunately the Version on the GamePass/Microsoft Store is outdated before the Living Large Update.
For that reason the Mod won't work with that version unfortunately.
