### ISSUE TITLE
Subnautica Zero : Snap turn stops working then works again. Possible conflict ?

### ISSUE THREAD

**Issue by Kozatiju** [Okabintaro/SubmersedVR#75]
Hi ! Each time I'm using the mod I have the snap turn that stops working with the right controller ( quest 2 ) then it comes back after a while. I'm early in the game so I don't think there is a possible confilct with a particular object. I don't have the issue with SubmersedVR for Subnautica 1. Would you have any idea why this issue happens randomly but frequently ?

Thanks again for this great mod port and your attention :-)

**Comment by jbusfield** [comment]
This issue should be fixed with version 0.5.0 https://github.com/jbusfield/SubmersedVR/releases/tag/0.5.0-bz. Please confirm.
