### ISSUE TITLE
[Quest 2] Can't put tools on hotbar?

### ISSUE THREAD

**Issue by ApolloHusky** [Okabintaro/SubmersedVR#89]
Sorry if this is a dumb question but how can I put tools on my hotbar? I made a survival knife but I can't figure out how to equip it. It says to press Y to assign to hotbar but I assume it means for xbox controller. Also it would be a cool feature if new items you make get automatically assigned to the hotbar

**Comment by Okabintaro** [comment]
Here you go: https://github.com/Okabintaro/SubmersedVR/issues/86
