### ISSUE TITLE
How do I run this if I have it via Epic?

### ISSUE THREAD

**Issue by SmokinDeist** [Okabintaro/SubmersedVR#90]
I would like to run this mod but I have the game via Epic. Is there a fix or anything I can do to get it up and running?

I also have a Quest 2 - Air Link, Virtual Desktop, Steam Link (Quest), and even the VR Air Bridge.

**Comment by xChris777** [comment]
Did you ever get this sorted? Trying to figure out how to make it work with my Epic copy.

**Comment by Okabintaro** [comment]
People have run this on Epic before: https://github.com/Okabintaro/SubmersedVR/issues/42#issuecomment-1605399270

I will try to add a guide for it in the future
